### ISSUE TITLE
Cannot find type MSCloudLoginConnectionProfile

### ISSUE THREAD

**Issue by kami-delaroz** [microsoft/Microsoft365DSC#3467]
I'm getting the error
`{Cannot find type [MSCloudLoginConnectionProfile]: verify that the assembly containing this type is loaded.}`
I saw it was defined in ConnectionProfile, but even after
`Import-Module -Name /root/.local/share/powershell/Modules/MSCloudLoginAssistant/1.0.114/ConnectionProfile.psm1`
I got the same error.

**Comment by andikrueger** [comment]
In which PS version are you working and on which OS?

**Comment by kami-delaroz** [comment]
I'm working with PS 7 and Ubuntu 22.04 os.
I know you officially don't support this os, but I managed to overcome most of the issues by manually import/install all needed modules.
But I'm not sure whether the ConnectionProfile module is indeed what is needed for MSCloudLoginConnectionProfile to be recognized, or there is something else.

**Comment by andikrueger** [comment]
The connection Profile is a class based powershell module within MSCloudLoginAssistant. 

https://github.com/microsoft/MSCloudLoginAssistant/blob/Dev/Modules/MSCloudLoginAssistant/ConnectionProfile.psm1

It’s crucial for MSCloudAssistant to function.

**Comment by DVDNetworksGithub** [comment]
I'm receiving this exact error as well.

All modules at latest versions as of 7/14/23. Windows 11, PS 5.1, fresh install in HyperV.

**Comment by kami-delaroz** [comment]
Did you try 
`Import-Module -Name /root/.local/share/powershell/Modules/MSCloudLoginAssistant/1.0.114/MSCloudLoginAssistant.psm1 -Force`
And then run `$Global:MSCloudLoginConnectionProfile = New-Object MSCloudLoginConnectionProfile` as a cmdlet in pwsh?

**Comment by andikrueger** [comment]
Just to add some information about PS 7 and other sub-systems: Right now, we do not support any other OS than Windows. 

For PS 7 information, we created this article:

https://microsoft365dsc.com/user-guide/get-started/powershell7-support/

**Comment by DVDNetworksGithub** [comment]
Errors I'm receiving are on Windows 11, PowerShell 5.1 .

**Comment by NikCharlebois** [comment]
Yes, but MSCloudLoginConnectionProfile isn't a declared object type, it simply is a global variable we're using across our solution to keep track of opened connectons to workloads. What are you trying to achieve exactly?

**Comment by kami-delaroz** [comment]
I switched to pwsh 7.3 and DSC beta version and this issue was resolved
